# Site
name: "Paper Tweeter"
title: "Paper Tweeter"
description: "All your papers. At tweet length."
logo: 'assets/images/twitterlogo.png'
favicon: 'assets/images/twitterlogo.png'
baseurl: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  realSharonZhou:
    name: Sharon Zhou
    avatar: "https://pbs.twimg.com/profile_images/1328750370798133253/yjVjhDTU_bigger.png"
    display_name: "@realSharonZhou"
    twitter: "https://twitter.com/realSharonZhou"
  oziadias:
    name: Ziad Obermeyer
    display_name: "@oziadias"
    avatar: https://pbs.twimg.com/profile_images/826520790334132226/V2Xhk6K4_400x400.jpg
    twitter: https://twitter.com/oziadias

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
